### ISSUE TITLE
Weekly scrum - [Nov 10]

### ISSUE THREAD

**Issue by Zhangjason308** [Waluiyeegi/SYSC-4806-Project#1]

**Comment by Triguy12** [comment]
What have I done this week? This week I made the Perk Manager class and the Product class. I have made adjustments to Main.c --> added code to get product and membership information and store in perk. Addutionally I have made minor changes to the remaining classes to ensure they function along side the additions I made to Main.c

What will I do next week? Next week I plan to implement the controllers that will be needed to handle GET and POST request

What is holding me back? N/A

**Comment by Zhangjason308** [comment]
**This week**
Completed design specifications for the classes to be incorporated. Updated the Perk, Membership and Product class, and worked on test cases for each of the following

**Next week**
Implement the CLI interface into a SpringBoot application along with the rest controllers, and templates in the backlog

**Blockers**
Midterm schedule this week

**Comment by Waluiyeegi** [comment]
This Week
Created Github Repository, Enabled CI and made sure it was up and running in production on Azure.  Created Member, Perk, and User Repositories.  Worked a little bit on user and perk.  Worked on viewing your perks on main.

Next Week
Integrate CLI and REST API functionalities into the Spring Boot application, including template implementation.

Blockers
Can't work on templates until controller is setup.

**Comment by nicholasyung1** [comment]
This week
Created Class requirements for User, Membership and Perk.

Next week
Add more functionality to each class above (user authentication, etc)

Blockers
Midterm and other assignment schedules this week.
